# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "padrino-responders"
  s.version = "0.1.6"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Kris 'nu7hatch' Kowalik"]
  s.date = "2013-01-17"
  s.description = "      This component is used to create slim controllers without unnecessery \n      and repetitive code.\n"
  s.email = "kriss.kowalik@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/padrino-responders.rb",
    "lib/padrino-responders/helpers/controller_helpers.rb",
    "lib/padrino-responders/helpers/response.rb",
    "lib/padrino-responders/locale/en.yml",
    "lib/padrino-responders/locale/pl.yml",
    "lib/padrino-responders/notifiers/flash_notifier.rb",
    "lib/padrino-responders/respond.rb",
    "lib/padrino-responders/responders/default.rb",
    "lib/padrino-responders/responders/jsend.rb",
    "lib/padrino-responders/status_codes.rb",
    "padrino-responders.gemspec",
    "test/padrino_responders_test.rb",
    "test/teststrap.rb"
  ]
  s.homepage = "http://github.com/nu7hatch/padrino-responders"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Simplified responders for Padrino framework"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<riot>, [">= 0.11.3"])
      s.add_development_dependency(%q<riot-rack>, [">= 0"])
      s.add_runtime_dependency(%q<padrino>, [">= 0.10.7"])
      s.add_runtime_dependency(%q<sinatra-flash>, [">= 0.3.0"])
    else
      s.add_dependency(%q<riot>, [">= 0.11.3"])
      s.add_dependency(%q<riot-rack>, [">= 0"])
      s.add_dependency(%q<padrino>, [">= 0.10.7"])
      s.add_dependency(%q<sinatra-flash>, [">= 0.3.0"])
    end
  else
    s.add_dependency(%q<riot>, [">= 0.11.3"])
    s.add_dependency(%q<riot-rack>, [">= 0"])
    s.add_dependency(%q<padrino>, [">= 0.10.7"])
    s.add_dependency(%q<sinatra-flash>, [">= 0.3.0"])
  end
end

